version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Running pre-build tests...
      - npm run lint || true
  build:
    commands:
      - echo Running unit tests...
      - npm test
  post_build:
    commands:
      - echo Running integration tests...
      - npm run test:integration || true
artifacts:
  files:
    - '**/*'
  reports:
    test-reports:
      files:
        - 'test-results.xml'
      base-directory: 'test-results'
